# Site wide configuration

title: Souliss
description: "Souliss SmartHome Framework"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: //plinioseniore.github.io/skinnybones
avatar: https://avatars0.githubusercontent.com/u/11448259?v=3&s=200

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Souliss Team
  web: http://www.souliss.net
  email: info@souliss.net
  twitter: soulissteam
  bio: ""
  avatar: logo160.png # 160x160 px image for author byline
  google:
    plus: +SoulissApp
    ad-client: 
    ad-slot: 
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
