# Site wide configuration

title: Prova1
description: "Descrizione1"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: plinioseniore.github.io/skinnybones/

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Souliss Team
  web: http://souliss.github.io
  email: info@souliss.net
  twitter: soulissteam
  bio: "Just another boring, tattooed, time traveling designer."
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: +MichaelRoseDesign
    ad-client: ca-pub-7328585512091257
    ad-slot: 3049671934
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
