safe: true
lsi: true
pygments: true
navigation:
  - text: Home
    url: /index.html
  - text: Archive
    url: /archive.html
baseurl: http://havvg.github.com
author:
  name: Toni Uebernickel
  email: tuebernickel@gmail.com
  nick: havvg
title: havvg's playground
strapline: Developing Software is Fun!
